[package]
name = "async-ffi"
version = "0.3.0"
edition = "2018"
description = "Make async Futures FFI compatible"
keywords = ["ffi", "async", "futures"]
categories = ["asynchronous", "network-programming"]
license = "MIT"
repository = "https://github.com/oxalica/async-ffi"
readme = "README.md"
exclude = ["/link_tests"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
